config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :cpm_projects do
      get 'delete'
    end
  end

  resources :products do
    get "delete"
  end
  resources :cpm_users

  namespace :admin do
    get 'index/index'
    get ''=>'index#index', :as=>'index'
    get 'index'=>'index#index', :as=>'admin_index'
  end

  resources :cpm_processes
  resources :cpm_priorities
  resources :cpm_issues
  resources :cpm_teams
  resources :cpm_histories
  resources :cpm_files

  resources :cpm_projects do
    get 'delete'
    get '/show' =>'cpm_projects#details', :as=> 'get_cpm_projects_show'
  end

  resources :cpm_tasks do
    get 'delete'
  end
  post 'cpm_tasks/search'=>'cpm_tasks#search'

  resources :cpm_comments

   root 'dashboard#index'

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/cpm_comment.rb
class CpmComment < ActiveRecord::Base
  belongs_to :cpm_project
  belongs_to :cpm_task
  belongs_to :cpm_user
  belongs_to :cpm_issue
  belongs_to :cpm_file
end

app/models/cpm_file.rb
class CpmFile < ActiveRecord::Base
  has_many :cpm_tasks
  has_many :cpm_issues
  has_many :cpm_comments
  belongs_to :cpm_user
end

app/models/cpm_history.rb
class CpmHistory < ActiveRecord::Base
  belongs_to :cpm_project
end

app/models/cpm_issue.rb
class CpmIssue < ActiveRecord::Base
  belongs_to :cpm_project
  has_many :cpm_comments
end

app/models/cpm_priority.rb
class CpmPriority < ActiveRecord::Base
  has_many :cpm_tasks
end

app/models/cpm_process.rb
class CpmProcess < ActiveRecord::Base
  has_many :cpm_tasks
end

app/models/cpm_project.rb
class CpmProject < ActiveRecord::Base
  has_and_belongs_to_many :cpm_users, through: :cpm_users
  has_many :cpm_histories
  has_many :cpm_comments
  has_many :cpm_tasks
  has_many :cpm_issues
  accepts_nested_attributes_for :cpm_users

  attr_accessible :name, :cpm_user_id, :start_date, :end_date,:status
  validates :name, presence: true

  def self.search(query)
    where("name like ?", "%#{query}%")
  end

end

app/models/cpm_task.rb
class CpmTask < ActiveRecord::Base
  belongs_to :cpm_project
  belongs_to :cpm_user
  belongs_to :cpm_process
  belongs_to :cpm_priority
  has_many :cpm_comments

  attr_accessible :name, :cpm_user_id, :cpm_process_id,:cpm_priority_id,:man_hour
  validates :name, presence: true

end

app/models/cpm_team.rb
class CpmTeam < ActiveRecord::Base
  has_many :cpm_users
end

app/models/cpm_user.rb
class CpmUser < ActiveRecord::Base
    has_many :cpm_files
    belongs_to  :cpm_team
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :price
  validates :name, presence: true
end

app/controllers/cpm_histories_controller.rb
class CpmHistoriesController < ApplicationController
  before_action :set_cpm_history, only: [:show, :edit, :update, :destroy]

  # GET /cpm_histories
  # GET /cpm_histories.json
  def index
    @cpm_histories = CpmHistory.all
  end

  # GET /cpm_histories/1
  # GET /cpm_histories/1.json
  def show
  end

  # GET /cpm_histories/new
  def new
    @cpm_history = CpmHistory.new
  end

  # GET /cpm_histories/1/edit
  def edit
  end

  # POST /cpm_histories
  # POST /cpm_histories.json
  def create
    @cpm_history = CpmHistory.new(cpm_history_params)

    respond_to do |format|
      if @cpm_history.save
        format.html { redirect_to @cpm_history, notice: 'Cpm history was successfully created.' }
        format.json { render :show, status: :created, location: @cpm_history }
      else
        format.html { render :new }
        format.json { render json: @cpm_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cpm_histories/1
  # PATCH/PUT /cpm_histories/1.json
  def update
    respond_to do |format|
      if @cpm_history.update(cpm_history_params)
        format.html { redirect_to @cpm_history, notice: 'Cpm history was successfully updated.' }
        format.json { render :show, status: :ok, location: @cpm_history }
      else
        format.html { render :edit }
        format.json { render json: @cpm_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cpm_histories/1
  # DELETE /cpm_histories/1.json
  def destroy
    @cpm_history.destroy
    respond_to do |format|
      format.html { redirect_to cpm_histories_url, notice: 'Cpm history was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cpm_history
      @cpm_history = CpmHistory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cpm_history_params
      params.require(:cpm_history).permit(:cpm_user_id, :name, :cpm_project_id, :cpm_task_id, :cpm_issue_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title (page_title='')
    base_title='CMCSoft'
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  def show_field_error(model, field)
    s=""

    if !model.errors[field].empty?
      s =
          <<-EOHTML
                   <div id="error_message">
                     #{model.errors[field][0]}
                   </div>
      EOHTML
    end

    s.html_safe
  end
end

app/helpers/cpm_files_helper.rb
module CpmFilesHelper
end

app/helpers/cpm_histories_helper.rb
module CpmHistoriesHelper
end

app/helpers/cpm_issues_helper.rb
module CpmIssuesHelper
end

app/helpers/cpm_tasks_helper.rb
module CpmTasksHelper
end

app/helpers/cpm_teams_helper.rb
module CpmTeamsHelper
end

app/helpers/cpm_users_helper.rb
module CpmUsersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
    session[:user_permit]=user.permit
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end


  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= CpmUser.find_by(id: session[:user_id])
    elsif (user_id = cookies.signed[:user_id])
      user = CpmUser.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default='')
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/views/cpm_histories/_form.html.erb
<%= form_for(@cpm_history) do |f| %>
  <% if @cpm_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cpm_history.errors.count, "error") %> prohibited this cpm_history from being saved:</h2>

      <ul>
      <% @cpm_history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cpm_user_id %><br>
    <%= f.number_field :cpm_user_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cpm_project_id %><br>
    <%= f.number_field :cpm_project_id %>
  </div>
  <div class="field">
    <%= f.label :cpm_task_id %><br>
    <%= f.number_field :cpm_task_id %>
  </div>
  <div class="field">
    <%= f.label :cpm_issue_id %><br>
    <%= f.number_field :cpm_issue_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cpm_histories/edit.html.erb
<h1>Editing Cpm History</h1>

<%= render 'form' %>

<%= link_to 'Show', @cpm_history %> |
<%= link_to 'Back', cpm_histories_path %>

app/views/cpm_histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cpm Histories</h1>

<table>
  <thead>
    <tr>
      <th>Cpm user</th>
      <th>Name</th>
      <th>Cpm project</th>
      <th>Cpm task</th>
      <th>Cpm issue</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cpm_histories.each do |cpm_history| %>
      <tr>
        <td><%= cpm_history.cpm_user_id %></td>
        <td><%= cpm_history.name %></td>
        <td><%= cpm_history.cpm_project_id %></td>
        <td><%= cpm_history.cpm_task_id %></td>
        <td><%= cpm_history.cpm_issue_id %></td>
        <td><%= link_to 'Show', cpm_history %></td>
        <td><%= link_to 'Edit', edit_cpm_history_path(cpm_history) %></td>
        <td><%= link_to 'Destroy', cpm_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cpm history', new_cpm_history_path %>

app/views/cpm_histories/new.html.erb
<h1>New Cpm History</h1>

<%= render 'form' %>

<%= link_to 'Back', cpm_histories_path %>

app/views/cpm_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cpm user:</strong>
  <%= @cpm_history.cpm_user_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @cpm_history.name %>
</p>

<p>
  <strong>Cpm project:</strong>
  <%= @cpm_history.cpm_project_id %>
</p>

<p>
  <strong>Cpm task:</strong>
  <%= @cpm_history.cpm_task_id %>
</p>

<p>
  <strong>Cpm issue:</strong>
  <%= @cpm_history.cpm_issue_id %>
</p>

<%= link_to 'Edit', edit_cpm_history_path(@cpm_history) %> |
<%= link_to 'Back', cpm_histories_path %>