config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :cpm_projects do
      get 'delete'
    end
  end

  resources :products do
    get "delete"
  end
  resources :cpm_users

  namespace :admin do
    get 'index/index'
    get ''=>'index#index', :as=>'index'
    get 'index'=>'index#index', :as=>'admin_index'
  end

  resources :cpm_processes
  resources :cpm_priorities
  resources :cpm_issues
  resources :cpm_teams
  resources :cpm_histories
  resources :cpm_files

  resources :cpm_projects do
    get 'delete'
    get '/show' =>'cpm_projects#details', :as=> 'get_cpm_projects_show'
  end

  resources :cpm_tasks do
    get 'delete'
  end
  post 'cpm_tasks/search'=>'cpm_tasks#search'

  resources :cpm_comments

   root 'dashboard#index'

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/cpm_comment.rb
class CpmComment < ActiveRecord::Base
  belongs_to :cpm_project
  belongs_to :cpm_task
  belongs_to :cpm_user
  belongs_to :cpm_issue
  belongs_to :cpm_file
end

app/models/cpm_file.rb
class CpmFile < ActiveRecord::Base
  has_many :cpm_tasks
  has_many :cpm_issues
  has_many :cpm_comments
  belongs_to :cpm_user
end

app/models/cpm_history.rb
class CpmHistory < ActiveRecord::Base
  belongs_to :cpm_project
end

app/models/cpm_issue.rb
class CpmIssue < ActiveRecord::Base
  belongs_to :cpm_project
  has_many :cpm_comments
end

app/models/cpm_priority.rb
class CpmPriority < ActiveRecord::Base
  has_many :cpm_tasks
end

app/models/cpm_process.rb
class CpmProcess < ActiveRecord::Base
  has_many :cpm_tasks
end

app/models/cpm_project.rb
class CpmProject < ActiveRecord::Base
  has_and_belongs_to_many :cpm_users, through: :cpm_users
  has_many :cpm_histories
  has_many :cpm_comments
  has_many :cpm_tasks
  has_many :cpm_issues
  accepts_nested_attributes_for :cpm_users

  attr_accessible :name, :cpm_user_id, :start_date, :end_date,:status
  validates :name, presence: true

  def self.search(query)
    where("name like ?", "%#{query}%")
  end

end

app/models/cpm_task.rb
class CpmTask < ActiveRecord::Base
  belongs_to :cpm_project
  belongs_to :cpm_user
  belongs_to :cpm_process
  belongs_to :cpm_priority
  has_many :cpm_comments

  attr_accessible :name, :cpm_user_id, :cpm_process_id,:cpm_priority_id,:man_hour
  validates :name, presence: true

end

app/models/cpm_team.rb
class CpmTeam < ActiveRecord::Base
  has_many :cpm_users
end

app/models/cpm_user.rb
class CpmUser < ActiveRecord::Base
    has_many :cpm_files
    belongs_to  :cpm_team
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :price
  validates :name, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  layout 'modal/application'
  respond_to :html, :js

  def index
    @products = Product.all

  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @products = Product.all
    @product = Product.create(product_params)
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @products = Product.all
    @product = Product.find(params[:id])
    @product.update_attributes(product_params)
  end

  def delete
    @product = Product.find(params[:product_id])
  end

  def destroy
    @products = Product.all
    @product = Product.find(params[:id])
    @product.destroy
  end

  private
  def product_params
    params.require(:product).permit(:name, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title (page_title='')
    base_title='CMCSoft'
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  def show_field_error(model, field)
    s=""

    if !model.errors[field].empty?
      s =
          <<-EOHTML
                   <div id="error_message">
                     #{model.errors[field][0]}
                   </div>
      EOHTML
    end

    s.html_safe
  end
end

app/helpers/cpm_comments_helper.rb
module CpmCommentsHelper
end

app/helpers/cpm_files_helper.rb
module CpmFilesHelper
end

app/helpers/cpm_issues_helper.rb
module CpmIssuesHelper
end

app/helpers/cpm_tasks_helper.rb
module CpmTasksHelper
end

app/helpers/cpm_teams_helper.rb
module CpmTeamsHelper
end

app/helpers/cpm_users_helper.rb
module CpmUsersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
    session[:user_permit]=user.permit
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end


  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= CpmUser.find_by(id: session[:user_id])
    elsif (user_id = cookies.signed[:user_id])
      user = CpmUser.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default='')
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/views/products/_delete.html.erb
<div class="modal-header">
  <h3>Delete Product</h3>
</div>
<div class="modal-body">
<ul class="errors"></ul>
Are you sure you wish to delete <b><%= @product.name %></b>?
</div>
<div class="modal-footer">
  <%= link_to "Yes, Delete This Product", product_path(@product), method: :delete, remote: true, class: "btn btn-danger" %>
  <%= link_to "No, Please Don't", "#", class: "btn", data: { dismiss: "modal" } %>
</div>

app/views/products/_edit.html.erb
<div class="modal-header">
  <h3><%= "Editing #{@product.name}" %></h3>
</div>
<%= render "form" %>

app/views/products/_form.html.erb
<%= form_for @product, remote: true, html: { class: "form-horizontal", style: "display:inline;" } do |f| %>
  <div class="modal-body">
    <ul class="errors"></ul>

    <div class="control-group">
      <%= f.label :name, class:"control-label" %>
      <div class="controls">
        <%= f.text_field :name %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :price, class: "control-label" %>
      <div class="controls">
        <%= f.text_field :price %>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
  </div>
<% end %>

app/views/products/_index.html.erb
<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= number_to_currency product.price %></td>
    <td><%= link_to "Edit", edit_product_path(product), remote: true, class: "btn" %></td>
    <td><%= link_to "Delete", product_delete_path(product), remote: true, class: "btn btn-danger" %></td>
  </tr>
<% end %>

app/views/products/_new.html.erb
<div class="modal-header">
<h3>New Product</h3>
</div>
<%= render "form" %>

app/views/products/_save.js.erb
$("ul.errors").html("")
<% if @product.errors.any? %>
  <% @product.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".product-index").html("<%= escape_javascript(render 'index') %>")
  $("#product-modal").modal("hide")
<% end %>

app/views/products/create.js.erb
alert('create');
<%= render "save" %>

app/views/products/delete.js.erb
$("#product-modal").html("<%= escape_javascript(render 'delete') %>")
$("#product-modal").modal("show")

app/views/products/destroy.js.erb
<%= render 'save' %>

app/views/products/edit.js.erb
$("#product-modal").html("<%= escape_javascript(render 'edit') %>")
$("#product-modal").modal("show")

app/views/products/index.html.erb
<div class="container">
  <div class="well">
    <%= link_to "New Product", new_product_path, remote: true, class: "btn btn-primary" %>
  </div>
  <div class="new-product"></div>
  
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    </thead>
    <tbody class="product-index">
      <%= render "index" %>
    </tbody>
  </table>
</div>
<div id="product-modal" class="modal hide fade"></div>

app/views/products/new.js.erb
$("#product-modal").html("<%= escape_javascript(render 'new') %>")
$("#product-modal").modal("show")

app/views/products/update.js.erb
<%= render "save" %>